import { UserDataApiResponse } from 'auth-api-sdk';

export interface User {

    id?: number;
    firstName?: string;
    lastName?: string;
    displayName: string;
    passwordAutoGenerated: boolean;
    emailAddress: string;
    phoneNumber?: string;
    data?: Array<UserDataApiResponse>;
}
