import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, UrlTree, Router } from '@angular/router';
import { Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { AuthenticationService } from '../services/authentication.service';
import { SessionStarter } from '../session/session-starter';

@Injectable({
  providedIn: 'root'
})
export class ActiveUserGuard implements CanActivate {

  constructor(
    private router: Router,
    private authenticationService: AuthenticationService,
    private sessionService: SessionStarter) { }

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {

    const queryParams = {
      redirectTo: state.url
    };

    return this.authenticationService.getUser()
      .pipe(map((user => {
        if (!user) {
          this.sessionService.startSession(next, state);
          return false;
        }

        if (user.passwordAutoGenerated) {
          this.router.navigate(['/change-password'], { queryParams });
          return false;
        }

        return true;
      })))
      .pipe(catchError((err: any, caught: Observable<any>) => {
        // this.router.navigate(['/login'], { queryParams });
        this.sessionService.startSession(next, state);
        return of(false);
      }));
  }

}
